# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asuransi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(343, 487)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 110, 231, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layananJudul_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.layananJudul_label.setFont(font)
        self.layananJudul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.layananJudul_label.setObjectName("layananJudul_label")
        self.verticalLayout.addWidget(self.layananJudul_label)
        self.layanan_layout_form = QtWidgets.QFormLayout()
        self.layanan_layout_form.setHorizontalSpacing(10)
        self.layanan_layout_form.setObjectName("layanan_layout_form")
        self.asuransi_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.asuransi_label.setObjectName("asuransi_label")
        self.layanan_layout_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.asuransi_label)
        self.asuransi_combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.asuransi_combo.setObjectName("asuransi_combo")
        self.layanan_layout_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.asuransi_combo)
        self.tes_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tes_label.setObjectName("tes_label")
        self.layanan_layout_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tes_label)
        self.tes_combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tes_combo.setObjectName("tes_combo")
        self.layanan_layout_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tes_combo)
        self.kadaluwarsa_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kadaluwarsa_label.setObjectName("kadaluwarsa_label")
        self.layanan_layout_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kadaluwarsa_label)
        self.kadaluwarsa_dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.kadaluwarsa_dateEdit.setObjectName("kadaluwarsa_dateEdit")
        self.layanan_layout_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kadaluwarsa_dateEdit)
        self.pilih_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pilih_button.setObjectName("pilih_button")
        self.layanan_layout_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pilih_button)
        self.verticalLayout.addLayout(self.layanan_layout_form)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.layananJudul_label.setText(_translate("Form", "LAYANAN ASURANSI"))
        self.asuransi_label.setText(_translate("Form", "Id Asuransi :"))
        self.tes_label.setText(_translate("Form", "Id Tes :"))
        self.kadaluwarsa_label.setText(_translate("Form", "Masa Berlaku :"))
        self.pilih_button.setText(_translate("Form", "PILIH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
