# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(349, 504)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 241, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.judul_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.judul_label.setFont(font)
        self.judul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.judul_label.setObjectName("judul_label")
        self.verticalLayout.addWidget(self.judul_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.dokter_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dokter_label.setObjectName("dokter_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dokter_label)
        self.pasien_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pasien_label.setObjectName("pasien_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pasien_label)
        self.dokter_combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.dokter_combo.setObjectName("dokter_combo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dokter_combo)
        self.pasien_combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.pasien_combo.setObjectName("pasien_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pasien_combo)
        self.verticalLayout.addLayout(self.formLayout)
        self.teks_textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.teks_textEdit.setObjectName("teks_textEdit")
        self.verticalLayout.addWidget(self.teks_textEdit)
        self.kirim_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.kirim_button.setObjectName("kirim_button")
        self.verticalLayout.addWidget(self.kirim_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.judul_label.setText(_translate("Form", "Chat"))
        self.dokter_label.setText(_translate("Form", "Id Dokter :"))
        self.pasien_label.setText(_translate("Form", "Id Pasien :"))
        self.kirim_button.setText(_translate("Form", "KIRIM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
