# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(386, 471)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 60, 251, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.judul_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.judul_label.setFont(font)
        self.judul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.judul_label.setObjectName("judul_label")
        self.verticalLayout.addWidget(self.judul_label)
        self.artikel_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.artikel_button.setObjectName("artikel_button")
        self.verticalLayout.addWidget(self.artikel_button)
        self.chat_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.chat_button.setEnabled(True)
        self.chat_button.setObjectName("chat_button")
        self.verticalLayout.addWidget(self.chat_button)
        self.scan_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.scan_button.setObjectName("scan_button")
        self.verticalLayout.addWidget(self.scan_button)
        self.tesLab_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tesLab_button.setObjectName("tesLab_button")
        self.verticalLayout.addWidget(self.tesLab_button)
        self.janji_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.janji_button.setObjectName("janji_button")
        self.verticalLayout.addWidget(self.janji_button)
        self.asuransi_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.asuransi_button.setObjectName("asuransi_button")
        self.verticalLayout.addWidget(self.asuransi_button)
        self.tagihan_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tagihan_button.setObjectName("tagihan_button")
        self.verticalLayout.addWidget(self.tagihan_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.judul_label.setText(_translate("Form", "APLIKASI \"CHECK UP\""))
        self.artikel_button.setText(_translate("Form", "ARTIKEL KESEHATAN"))
        self.chat_button.setText(_translate("Form", "CHAT"))
        self.scan_button.setText(_translate("Form", "SCAN SUHU TUBUH"))
        self.tesLab_button.setText(_translate("Form", "TES KESEHATAN"))
        self.janji_button.setText(_translate("Form", "JANJI MEDIS"))
        self.asuransi_button.setText(_translate("Form", "LAYANAN ASURANSI"))
        self.tagihan_button.setText(_translate("Form", "TAGIHAN PEMBAYARAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
