# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jadwal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(392, 515)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 30, 221, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.judul_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.judul_label.setFont(font)
        self.judul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.judul_label.setObjectName("judul_label")
        self.verticalLayout.addWidget(self.judul_label)
        self.janjimedis_layout_form = QtWidgets.QFormLayout()
        self.janjimedis_layout_form.setHorizontalSpacing(10)
        self.janjimedis_layout_form.setVerticalSpacing(20)
        self.janjimedis_layout_form.setObjectName("janjimedis_layout_form")
        self.pesanan_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pesanan_label.setObjectName("pesanan_label")
        self.janjimedis_layout_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pesanan_label)
        self.dokter_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dokter_label.setObjectName("dokter_label")
        self.janjimedis_layout_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dokter_label)
        self.laborat_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.laborat_label.setObjectName("laborat_label")
        self.janjimedis_layout_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.laborat_label)
        self.pasien_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pasien_label.setObjectName("pasien_label")
        self.janjimedis_layout_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pasien_label)
        self.tempat_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tempat_label.setObjectName("tempat_label")
        self.janjimedis_layout_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tempat_label)
        self.tempat_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tempat_lineEdit.setObjectName("tempat_lineEdit")
        self.janjimedis_layout_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tempat_lineEdit)
        self.pesanan_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.pesanan_comboBox.setObjectName("pesanan_comboBox")
        self.janjimedis_layout_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pesanan_comboBox)
        self.dokter_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.dokter_comboBox.setObjectName("dokter_comboBox")
        self.janjimedis_layout_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dokter_comboBox)
        self.laborat_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.laborat_comboBox.setObjectName("laborat_comboBox")
        self.janjimedis_layout_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.laborat_comboBox)
        self.pasien_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.pasien_comboBox.setObjectName("pasien_comboBox")
        self.janjimedis_layout_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pasien_comboBox)
        self.jadwal_timeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.jadwal_timeEdit.setObjectName("jadwal_timeEdit")
        self.janjimedis_layout_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.jadwal_timeEdit)
        self.jadwal_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.jadwal_label.setObjectName("jadwal_label")
        self.janjimedis_layout_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.jadwal_label)
        self.daftar_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.daftar_button.setObjectName("daftar_button")
        self.janjimedis_layout_form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.daftar_button)
        self.verticalLayout.addLayout(self.janjimedis_layout_form)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.judul_label.setText(_translate("Form", "JANJI MEDIS"))
        self.pesanan_label.setText(_translate("Form", "Id Pesanan :"))
        self.dokter_label.setText(_translate("Form", "Id Dokter :"))
        self.laborat_label.setText(_translate("Form", "Id Laborat :"))
        self.pasien_label.setText(_translate("Form", "Id Pasien :"))
        self.tempat_label.setText(_translate("Form", "Tempat :"))
        self.jadwal_label.setText(_translate("Form", "Jadwal :"))
        self.daftar_button.setText(_translate("Form", "DAFTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
