# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(342, 490)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(90, 110, 161, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scanning_label = QtWidgets.QLabel(Form)
        self.scanning_label.setGeometry(QtCore.QRect(80, 100, 181, 181))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.scanning_label.setFont(font)
        self.scanning_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scanning_label.setText("")
        self.scanning_label.setObjectName("scanning_label")
        self.scanSuhu_label = QtWidgets.QLabel(Form)
        self.scanSuhu_label.setGeometry(QtCore.QRect(70, 50, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.scanSuhu_label.setFont(font)
        self.scanSuhu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.scanSuhu_label.setObjectName("scanSuhu_label")
        self.scan_button = QtWidgets.QPushButton(Form)
        self.scan_button.setGeometry(QtCore.QRect(110, 300, 121, 31))
        self.scan_button.setObjectName("scan_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.scanSuhu_label.setText(_translate("Form", "SCAN SUHU TUBUH"))
        self.scan_button.setText(_translate("Form", "SCAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
