# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tesLab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 493)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 30, 231, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.judul_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.judul_label.setFont(font)
        self.judul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.judul_label.setObjectName("judul_label")
        self.verticalLayout.addWidget(self.judul_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.tes_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tes_label.setObjectName("tes_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tes_label)
        self.tes_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tes_comboBox.setObjectName("tes_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tes_comboBox)
        self.pesanan_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pesanan_label.setObjectName("pesanan_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pesanan_label)
        self.pesanan_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.pesanan_comboBox.setObjectName("pesanan_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pesanan_comboBox)
        self.resep_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.resep_label.setObjectName("resep_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.resep_label)
        self.diagnosa_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.diagnosa_label.setObjectName("diagnosa_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.diagnosa_label)
        self.diagnosa_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.diagnosa_comboBox.setObjectName("diagnosa_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.diagnosa_comboBox)
        self.resep_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.resep_comboBox.setObjectName("resep_comboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.resep_comboBox)
        self.cek_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cek_button.setObjectName("cek_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cek_button)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.judul_label.setText(_translate("Form", "TES LABORATORIUM"))
        self.tes_label.setText(_translate("Form", "Id Tes :"))
        self.pesanan_label.setText(_translate("Form", "Id Pesanan :"))
        self.resep_label.setText(_translate("Form", "Resep obat :"))
        self.diagnosa_label.setText(_translate("Form", "Diagnosa :"))
        self.cek_button.setText(_translate("Form", "CEK HASIL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
