# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(343, 488)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 211, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.judul_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.judul_label.setFont(font)
        self.judul_label.setAlignment(QtCore.Qt.AlignCenter)
        self.judul_label.setObjectName("judul_label")
        self.verticalLayout.addWidget(self.judul_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.transaksi_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.transaksi_label.setObjectName("transaksi_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.transaksi_label)
        self.transaksi_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.transaksi_comboBox.setObjectName("transaksi_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.transaksi_comboBox)
        self.asuransi_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.asuransi_comboBox.setObjectName("asuransi_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.asuransi_comboBox)
        self.asuransi_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.asuransi_label.setObjectName("asuransi_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.asuransi_label)
        self.total_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.total_label.setObjectName("total_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.total_label)
        self.total_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.total_comboBox.setObjectName("total_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.total_comboBox)
        self.bayar_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bayar_button.setObjectName("bayar_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bayar_button)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.judul_label.setText(_translate("Form", "TRANSAKSI"))
        self.transaksi_label.setText(_translate("Form", "Id Transaksi :"))
        self.asuransi_label.setText(_translate("Form", "Id Asuransi :"))
        self.total_label.setText(_translate("Form", "Jumlah Tagihan :"))
        self.bayar_button.setText(_translate("Form", "BAYAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
